# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy project files
COPY pyproject.toml .
COPY src ./src

# Install the application
RUN pip install --no-cache-dir .

# Define default command
CMD ["logseq-mcp"]
